{
 "title": "Monitoring the RAG Project",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total of Questions Answered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) Total_Question_Answered\r\nFROM avaliacao \r\n--GROUP BY 1"
    }
   ]
  },
  {
   "title": "Feedbacks Filled by Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) Users_Filled_Feedback\r\nFROM feedback "
    }
   ]
  },
  {
   "title": "Users Satisfaction with the LLM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\r\n  COUNT(CASE WHEN is_satisfied = TRUE THEN id ELSE NULL END)/COUNT(id)::float AS Users_Satisfaction\r\nFROM feedback "
    }
   ]
  },
  {
   "title": "Time of Response of the LLM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_time,\r\n  response_time\r\nFROM avaliacao "
    }
   ]
  }
 ]
}